spring:
  application:
    name: springbootRedis_demo

  # Redis 相关配置
  redis:
    host: 127.0.0.1 # 本地redis服务器地址
    port: 6379 #默认端口号 6379
    #password:123456
    database: 0
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 4   # 连接池中的最大空闲连接
        max-wait: 1ms # 连接池最大阻塞时间
        min-idle: 0   # 连接池最小空闲连接
